.TH COMPASS-CLI "1" "June 2016" "compass-cli 0.12"
.SH NAME
compass-cli \- a remote procedure call client for Compass Coin.
.SH SYNOPSIS
compass-cli [options] <command> [params] \- Send command to Compass Coin.
.TP
compass-cli [options] help \- Asks Compass Coin for a list of supported commands.
.SH DESCRIPTION
This manual page documents the compass-cli program. compass-cli is an RPC client used to send commands to Compass Coin.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBcompassd\fP, \fBcompass.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
